services:
  sut:
    build: .
    command: "/wait-for-it.sh db:5432 -- /usr/bin/python3 /home/timetable/urnik/manage.py test friprosveta"
    environment:
      - DJANGO_SETTINGS_MODULE=urnik_fri.settings_example
    links:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=timetable
      - POSTGRES_DB=timetable
      - POSTGRES_PASSWORD=database_password
