# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friprosveta", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="study",
            old_name="shortName",
            new_name="short_name",
        )
    ]
