# Generated by Django 2.1.1 on 2018-09-30 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0002_auto_20180228_1129"),
        ("friprosveta", "0002_auto_20180228_1129"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="group_ptr",
        ),
        migrations.RemoveField(
            model_name="group",
            name="studies",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
