# Generated by ChatGPT on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friprosveta", "0005_activity_cycles_on_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="upn",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
