# Generated by OpenCode on 2026-07-02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friprosveta', '0006_student_upn'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='lecture_split',
            field=models.CharField(blank=True, choices=[('', 'Brez posebne želje'), ('3', '3 ure skupaj'), ('2-1', '2 + 1'), ('1-1-1', '1 + 1 + 1')], default='', help_text='Želena razdelitev triurnih predavanj.', max_length=16, verbose_name='Razdelitev predavanj'),
        ),
    ]
