# Generated by Django 5.2.9 on 2026-07-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friprosveta", "0007_activity_lecture_split"),
        ("timetable", "0019_solverconstraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityTypeSchedulingWindow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("LAB", "Laborant vaje"),
                            ("LV", "Laboratorijske vaje"),
                            ("AV", "Avditorne vaje"),
                            ("P", "Predavanja"),
                            ("TUT", "Tutorstvo"),
                            ("REP", "Repetitorij"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "ponedeljek"),
                            ("TUE", "torek"),
                            ("WED", "sreda"),
                            ("THU", "četrtek"),
                            ("FRI", "petek"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        choices=[
                            ("07:00", "07:00"),
                            ("08:00", "08:00"),
                            ("09:00", "09:00"),
                            ("10:00", "10:00"),
                            ("11:00", "11:00"),
                            ("12:00", "12:00"),
                            ("13:00", "13:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("16:00", "16:00"),
                            ("17:00", "17:00"),
                            ("18:00", "18:00"),
                            ("19:00", "19:00"),
                            ("20:00", "20:00"),
                            ("21:00", "21:00"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "end",
                    models.CharField(
                        choices=[
                            ("07:00", "07:00"),
                            ("08:00", "08:00"),
                            ("09:00", "09:00"),
                            ("10:00", "10:00"),
                            ("11:00", "11:00"),
                            ("12:00", "12:00"),
                            ("13:00", "13:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("16:00", "16:00"),
                            ("17:00", "17:00"),
                            ("18:00", "18:00"),
                            ("19:00", "19:00"),
                            ("20:00", "20:00"),
                            ("21:00", "21:00"),
                            ("22:00", "22:00"),
                        ],
                        max_length=5,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_type_scheduling_windows",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("timetable", "activity_type", "day"),
                        name="activity_type_scheduling_window_unique_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("start__lt", models.F("end"))),
                        name="activity_type_scheduling_window_start_before_end",
                    ),
                ],
            },
        ),
    ]
