# Generated by Django 5.2.9 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friprosveta", "0008_activitytypeschedulingwindow"),
        ("timetable", "0019_solverconstraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityRealizationSchedulingWindow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "ponedeljek"),
                            ("TUE", "torek"),
                            ("WED", "sreda"),
                            ("THU", "četrtek"),
                            ("FRI", "petek"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("07:00", "07:00"),
                            ("08:00", "08:00"),
                            ("09:00", "09:00"),
                            ("10:00", "10:00"),
                            ("11:00", "11:00"),
                            ("12:00", "12:00"),
                            ("13:00", "13:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("16:00", "16:00"),
                            ("17:00", "17:00"),
                            ("18:00", "18:00"),
                            ("19:00", "19:00"),
                            ("20:00", "20:00"),
                            ("21:00", "21:00"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "end",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("07:00", "07:00"),
                            ("08:00", "08:00"),
                            ("09:00", "09:00"),
                            ("10:00", "10:00"),
                            ("11:00", "11:00"),
                            ("12:00", "12:00"),
                            ("13:00", "13:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("16:00", "16:00"),
                            ("17:00", "17:00"),
                            ("18:00", "18:00"),
                            ("19:00", "19:00"),
                            ("20:00", "20:00"),
                            ("21:00", "21:00"),
                            ("22:00", "22:00"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("unrestricted", models.BooleanField(default=False)),
                (
                    "realization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_window_overrides",
                        to="timetable.activityrealization",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_realization_scheduling_windows",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("timetable", "realization", "day"),
                        name="activity_realization_scheduling_window_unique_day",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("end__isnull", True),
                                ("start__isnull", True),
                                ("unrestricted", True),
                            )
                            | models.Q(
                                ("end__isnull", False),
                                ("start__isnull", False),
                                ("start__lt", models.F("end")),
                                ("unrestricted", False),
                            )
                        ),
                        name="activity_realization_scheduling_window_valid_bounds",
                    ),
                ],
            },
        ),
    ]
