# Generated by Django 5.2.9 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friprosveta", "0009_activityrealizationschedulingwindow"),
        ("timetable", "0019_solverconstraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSchedulingWindow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "ponedeljek"),
                            ("TUE", "torek"),
                            ("WED", "sreda"),
                            ("THU", "četrtek"),
                            ("FRI", "petek"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        blank=True,
                        choices=[
                            (f"{hour:02}:00", f"{hour:02}:00") for hour in range(7, 22)
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "end",
                    models.CharField(
                        blank=True,
                        choices=[
                            (f"{hour:02}:00", f"{hour:02}:00") for hour in range(7, 23)
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("unrestricted", models.BooleanField(default=False)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_window_overrides",
                        to="timetable.teacher",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_scheduling_windows",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("timetable", "teacher", "day"),
                        name="teacher_scheduling_window_unique_day",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("end__isnull", True),
                                ("start__isnull", True),
                                ("unrestricted", True),
                            )
                            | models.Q(
                                ("end__isnull", False),
                                ("start__isnull", False),
                                ("start__lt", models.F("end")),
                                ("unrestricted", False),
                            )
                        ),
                        name="teacher_scheduling_window_valid_bounds",
                    ),
                ],
            },
        ),
    ]
