# Generated by Django 4.1.4 on 2022-12-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0004_group_visible_in_navigation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="mustNotOverlap",
            field=models.ManyToManyField(blank=True, to="timetable.activity"),
        ),
    ]
