# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friprosveta', '0008_group'),
        ('timetable', '0010_auto_20171227_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_finalized', models.DateTimeField(blank=True, null=True)),
                ('date_cancelled', models.DateTimeField(blank=True, null=True)),
                ('allocation_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_exchanges', to='timetable.Allocation')),
                ('allocation_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_exchanges', to='timetable.Allocation')),
                ('finalizer_exchange', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalized_exchange', to='exchange.Exchange')),
                ('initiator_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_exchanges', to='friprosveta.Student')),
                ('requested_finalizer_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_exchange_finalizations', to='friprosveta.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_allowed', models.BooleanField(default=True)),
                ('exchange_deadline', models.DateField(blank=True, null=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_preference', to='friprosveta.Subject')),
            ],
        ),
    ]
