# Generated by Django 2.1.1 on 2018-09-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("timetable", "0002_auto_20180228_1129"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default", models.BooleanField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.Site"
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        help_text="Timetable to show on the given site",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.Timetable",
                        verbose_name="Urnik",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="groupvaluepreference",
            name="name",
            field=models.CharField(
                choices=[
                    ("MAXDAYSWEEK", "Max days per week"),
                    ("MINDAYSWEEK", "Min days per week"),
                    ("MAXHOURSDAY", "Max hours per day"),
                    ("MINHOURSDAY", "Min hours per day"),
                    ("MAXHOURSCONT", "Max hours continuously"),
                    ("MAXSPANDAY", "Max span per day"),
                    ("MAXGAPSDAY", "Max gaps per day"),
                    ("MAXGAPSWEEK", "Max gaps per week"),
                    ("MAXCHANGESWEEK", "Max building changes per week"),
                    ("MAXCHANGESDAY", "Max building changes per day"),
                    ("MINCHANGEGAP", "Min gap between changes"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="tagdescriptivepreference",
            name="typename",
            field=models.CharField(
                choices=[
                    ("COMMENT", "A random comment"),
                    ("NOOVERLAP", "Must not overlap"),
                    ("GROUPED", "Activities must be grouped"),
                    ("CONSECUTIVE", "Realizations must be consecutive"),
                    ("ENDSSTUDENTSDAY", "Activity ends student's day"),
                    (
                        "SAMEDAY",
                        "A set of activities/realizations must be on the same day",
                    ),
                    (
                        "SAMESTARTINGTIME",
                        "A set of activities/realizations must start on the same time (day + hour)",
                    ),
                ],
                default="COMMENT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tagvaluepreference",
            name="name",
            field=models.CharField(
                choices=[
                    ("MAXDAYSWEEK", "Max days per week for a tag"),
                    ("MINDAYSWEEK", "Min days per week for a tag"),
                    ("MAXHOURSDAY", "Max hours per day for a tag"),
                    ("MINHOURSDAY", "Min hours per day for a tag"),
                    ("MAXSPANDAY", "Max span per day"),
                    ("MAXGAPSDAY", "Max gaps per day for a tag"),
                    ("MAXGAPSWEEK", "Max gaps per week for a tag"),
                    ("MAXCHANGESWEEK", "Max building changes per week"),
                    ("MAXCHANGESDAY", "Max building changes per day"),
                    ("MINCHANGEGAP", "Min gap between changes"),
                    ("MINACTIVITYGAP", "Min gap between a set of activities"),
                    (
                        "MULSIZE",
                        "Multiply group size for activities with this tag by a factor",
                    ),
                    ("SHRINKGROUPS", "Group size for activity -> Group size - VALUE"),
                    (
                        "MAXROOMSREALIZATIONS",
                        "Maximal number of different rooms used by the set of realization",
                    ),
                    (
                        "TAGMAXHOURSDAILY",
                        "Mas hours daily for given tag for given students",
                    ),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="teacherdescriptivepreference",
            name="typename",
            field=models.CharField(
                choices=[
                    ("COMMENT", "A random comment"),
                    ("NOOVERLAP", "Must not overlap"),
                    ("GROUPED", "Activities must be grouped"),
                    ("CONSECUTIVE", "Realizations must be consecutive"),
                    ("ENDSSTUDENTSDAY", "Activity ends student's day"),
                    (
                        "SAMEDAY",
                        "A set of activities/realizations must be on the same day",
                    ),
                    (
                        "SAMESTARTINGTIME",
                        "A set of activities/realizations must start on the same time (day + hour)",
                    ),
                ],
                default="COMMENT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="teachervaluepreference",
            name="name",
            field=models.CharField(
                choices=[
                    ("MAXDAYSWEEK", "Max days per week"),
                    ("MINDAYSWEEK", "Min days per week"),
                    ("MAXHOURSDAY", "Max hours per day"),
                    ("MINHOURSDAY", "Min hours per day"),
                    ("MAXHOURSCONT", "Max hours continuously"),
                    ("MAXSPANDAY", "Max span per day"),
                    ("MAXGAPSDAY", "Max gaps per day"),
                    ("MAXGAPSWEEK", "Max gaps per week"),
                    ("MAXCHANGESWEEK", "Max building changes per week"),
                    ("MAXCHANGESDAY", "Max building changes per day"),
                    ("MINCHANGEGAP", "Min gap between changes"),
                ],
                max_length=24,
            ),
        ),
    ]
