# Generated by Django 4.2.24 on 2025-09-27 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_activity_required_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_day', models.CharField(blank=True, choices=[('MON', 'ponedeljek'), ('TUE', 'torek'), ('WED', 'sreda'), ('THU', 'četrtek'), ('FRI', 'petek')], help_text='Preferred day for the trade', max_length=3, null=True)),
                ('desired_start_time', models.CharField(blank=True, choices=[('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], help_text='Preferred start time', max_length=5, null=True)),
                ('desired_duration', models.IntegerField(blank=True, help_text='Preferred duration in hours', null=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the trade request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this request expires (optional)', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Notes from the administrator about the approval/rejection')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Administrator who approved/rejected the trade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trades', to='timetable.teacher')),
                ('desired_allocation', models.ForeignKey(blank=True, help_text="Specific allocation desired, leave empty for 'any suitable'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_wanting', to='timetable.allocation')),
                ('matched_with', models.ForeignKey(blank=True, help_text='The trade request this one is matched with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_request', to='timetable.traderequest')),
                ('offered_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_offering', to='timetable.allocation')),
                ('requesting_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_made', to='timetable.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], default='PENDING_APPROVAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('executed_at', models.DateTimeField(blank=True, help_text='When the trade was actually executed', null=True)),
                ('executed_by', models.ForeignKey(blank=True, help_text='Who executed the trade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_trades', to='timetable.teacher')),
                ('request_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_request_1', to='timetable.traderequest')),
                ('request_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_request_2', to='timetable.traderequest')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Administrator who reviewed this match', null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='traderequest',
            index=models.Index(fields=['status', 'created_at'], name='timetable_t_status_38a006_idx'),
        ),
        migrations.AddIndex(
            model_name='traderequest',
            index=models.Index(fields=['requesting_teacher', 'status'], name='timetable_t_request_db04f6_idx'),
        ),
        migrations.AddIndex(
            model_name='traderequest',
            index=models.Index(fields=['offered_allocation'], name='timetable_t_offered_fbd2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='traderequest',
            index=models.Index(fields=['desired_allocation'], name='timetable_t_desired_c4e467_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradematch',
            unique_together={('request_1', 'request_2')},
        ),
    ]
