# Generated by Django 5.2.9 on 2025-12-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_traderequest_tradematch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heuristic',
        ),
    ]
