# Generated by Django 5.2.9 on 2025-12-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_delete_heuristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the resource group (e.g., 'Projection Equipment', 'Computer Labs')", max_length=255)),
                ('required', models.BooleanField(default=False, help_text='If checked, users must select at least one resource from this group')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['group__order', 'group__name', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within the group (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group this resource belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='timetable.resourcegroup'),
        ),
    ]
