# Generated by Django 5.2.9 on 2025-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_resourcegroup_alter_resource_options_resource_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcegroup',
            name='exactly_one',
            field=models.BooleanField(default=False, help_text='If checked, users must select exactly one resource from this group (not more, not less)'),
        ),
    ]
