# Generated by Django 5.2.9 on 2025-12-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_resourcegroup_exactly_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='teacher_rejected_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who rejected this trade offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_trade_offers', to='timetable.teacher'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='teacher_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason given by teacher for rejecting the trade'),
        ),
    ]
