# Generated by Django 5.2.9 on 2025-12-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_traderequest_teacher_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='desired_classroom',
            field=models.ForeignKey(blank=True, help_text='Preferred classroom for the new time slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_requests_desired_classroom', to='timetable.classroom'),
        ),
    ]
