# Generated by Django 5.2.9 on 2025-12-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_traderequest_desired_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='trading_enabled',
            field=models.BooleanField(default=True, help_text='Allow teachers to create and manage trade requests'),
        ),
    ]
