# Generated by ChatGPT on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0013_add_trading_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="studis_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
