# Generated by Django's makemigrations on 2026-02-11
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_traderequest_original_offered_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='original_desired_allocation',
            field=models.ForeignKey(blank=True, help_text='Desired allocation at request time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_requests_original_desired_allocation', to='timetable.allocation'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='original_desired_day',
            field=models.CharField(blank=True, choices=[('MON', 'ponedeljek'), ('TUE', 'torek'), ('WED', 'sreda'), ('THU', 'četrtek'), ('FRI', 'petek')], help_text='Preferred day at request time', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='original_desired_start_time',
            field=models.CharField(blank=True, choices=[('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], help_text='Preferred start time at request time', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='original_desired_duration',
            field=models.IntegerField(blank=True, help_text='Preferred duration in hours at request time', null=True),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='original_desired_classroom',
            field=models.ForeignKey(blank=True, help_text='Preferred classroom at request time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_requests_original_desired_classroom', to='timetable.classroom'),
        ),
    ]
