# Generated by OpenCode on 2026-07-02
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_traderequest_original_desired_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceIncompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_a', to='timetable.resource')),
                ('resource_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_b', to='timetable.resource')),
            ],
            options={
                'verbose_name_plural': 'resource incompatibilities',
            },
        ),
        migrations.AddField(
            model_name='timetable',
            name='min_physical_cycle_percentage',
            field=models.PositiveSmallIntegerField(default=100, help_text="Minimum percentage of an activity's cycles that teachers must request on site.", validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='resourceincompatibility',
            constraint=models.CheckConstraint(condition=models.Q(('resource_a', models.F('resource_b')), _negated=True), name='resource_incompatibility_distinct_resources'),
        ),
        migrations.AddConstraint(
            model_name='resourceincompatibility',
            constraint=models.UniqueConstraint(fields=('resource_a', 'resource_b'), name='unique_resource_incompatibility'),
        ),
    ]
