# Generated by OpenCode on 2026-07-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_resourceincompatibility_timetable_min_physical'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archived resources are hidden from requirement selection'),
        ),
    ]
