# Generated by Django 5.2.9 on 2026-07-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_resource_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolverConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('constraint_type', models.CharField(choices=[('NOOVERLAP', 'Realizations must not overlap'), ('GROUPED', 'Realizations must start together'), ('CONSECUTIVE', 'Realizations must be consecutive'), ('SAMEDAY', 'Realizations must be on the same day'), ('SAMESTARTINGTIME', 'Realizations must start at the same time'), ('ENDSSTUDENTSDAY', "Realization ends the students' day"), ('MAXROOMSREALIZATIONS', 'Maximum different rooms across realizations'), ('MAXDAYSWEEK', 'Maximum active days per week'), ('MINDAYSWEEK', 'Minimum active days per week'), ('MAXHOURSDAY', 'Maximum hours per day'), ('MAXHOURSCONT', 'Maximum continuous hours'), ('MINCHANGEGAP', 'Minimum gap between building changes')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('hard', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('activities', models.ManyToManyField(blank=True, to='timetable.activity')),
                ('classrooms', models.ManyToManyField(blank=True, to='timetable.classroom')),
                ('groups', models.ManyToManyField(blank=True, to='timetable.group')),
                ('realizations', models.ManyToManyField(blank=True, to='timetable.activityrealization')),
                ('teachers', models.ManyToManyField(blank=True, to='timetable.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_constraints', to='timetable.timetable')),
            ],
        ),
    ]
