# Generated by Django 5.2.9 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0020_alter_solverconstraint_constraint_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="allow_overlaps",
            field=models.BooleanField(
                default=False,
                help_text="Allow simultaneous allocations, for example for virtual rooms.",
            ),
        ),
        migrations.AlterField(
            model_name="solverconstraint",
            name="constraint_type",
            field=models.CharField(
                choices=[
                    ("NOOVERLAP", "Realizations must not overlap"),
                    ("GROUPED", "Realizations must start together"),
                    ("CONSECUTIVE", "Realizations must be consecutive"),
                    ("SAMEDAY", "Realizations must be on the same day"),
                    ("SAMESTARTINGTIME", "Realizations must start at the same time"),
                    ("ENDSSTUDENTSDAY", "Realization ends the students' day"),
                    ("MAXROOMSREALIZATIONS", "Maximum different rooms across realizations"),
                    ("MAXDAYSWEEK", "Maximum active days per week"),
                    ("MINDAYSWEEK", "Minimum active days per week"),
                    ("MAXHOURSDAY", "Maximum hours per day"),
                    ("MAXHOURSCONT", "Maximum continuous hours"),
                    ("MINCHANGEGAP", "Minimum gap between building changes"),
                    (
                        "MAXLECTUREHOURSDAY",
                        "Maximum lecture hours per day for a top-level group",
                    ),
                    ("FIXEDROOM", "Fixed room for activities or realizations"),
                ],
                max_length=32,
            ),
        ),
    ]
