# Generated by Django 5.2.9 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0021_classroom_allow_overlaps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="is_virtual",
            field=models.BooleanField(
                default=False,
                help_text="Marks a room for remote-delivery cycles.",
            ),
        ),
    ]
