# Generated by Django 3.2.12 on 2022-12-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friprosveta", "0003_auto_20180930_2347"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="ready_to_schedule",
            field=models.BooleanField(
                default=False,
                help_text="The activity is ready to be scheduled.",
                verbose_name="ready to schedule",
            ),
        ),
    ]
